[package]
name = "macro_example"
version = "0.1.0"
authors = ["Kevin Stenerson <developer@stenerson.me>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
combine = "3.8.1"
combine-proc-macro = "0.3.1"
crabwise-antlr-parser = { path = "../.." }
quote = "0.6.12"
